### ISSUE TITLE
Requested Changes to the data table for the PPP crispr studies

### ISSUE THREAD

**Issue by emcdonagh-OT** [opentargets/issues#2565]
_Please note, this list is a work in progress..._

**** 

1. [x] projectId: OTAR033: from 'studyOverview' remove the sentence "survival was measured" from all. 
2. [x] `diseaseFromSourceMappedId` needs to be consolidated across sources (`colorectal carcinoma` vs `colorectal cancer`).
3. [x] Integrate new versioning system for data files with Sarah, and display version in the data table on the PPP. 
4. [x] Find out correct study description and contrast for OTAR036 (Tau monomer vs aggregated). Update study spreadsheet. 
5. [x] Clarify contrast for OTAR035: awaiting this information from Ellie (after meeting Sofia)
6. [x] For OTVL: update data and biomarker assessment based on latest files provided by Panos (when submitted). This includes a new biomarker (and removal of CRIS biomarkers), and removal of several control genes.
7. [x] For OTVL: change wording for study overview to 'Cas9-expressing cell lines were transfected with gene-specific gRNAs in 384-well arrayed format. After 7 days in culture, endpoint viability was measured by CellTitreGlo'
8. [x] ENCORE: remove breast cancer data upon request from Emre
9. [x] Establish system for providing a warning about particular aspects of the data that may be inaccurate or incorrect
10. [x] For projectId OTAR2054: Add the study overview 'Identifying modulators of stress response in iNeurons'
11. [x] For projectId OTAR2054: change constrast to 'Enrichment of sgRNAs in low vs high CHOP populations under ER stress’ and 'Enrichment of sgRNAs in low vs high RBM3 populations under cooling’ (remove 'or depletion' from both contrasts)

**Comment by DSuveges** [comment]
Some of these tasks are related to how the input parameters of the data parsers are handled. I'm addressing them with one effort captured under #2582

**Comment by DSuveges** [comment]
The disease annotation for encore is now changed from `colorectal carcinoma - EFO_1001951` to `colorectal cancer    - EFO_0005842`. Now VL and encore data will show consistent annotation. (updated on commit [here](https://github.com/opentargets/evidence_datasource_parsers/pull/116/commits/033b3be48aba1fa99419d21a00d7e599eb833eeb))

**Comment by DSuveges** [comment]
VL comments are addressed by implementing the changes included in the new release.

**Comment by DSuveges** [comment]
All changes were implemented.

**Comment by buniello** [comment]
I am re-opening this issue as the Validation Lab team noticed that the CRIS biomarkers are still shown in the PPP and should be removed for the next release:

https://partner-platform.opentargets.org/evidence/ENSG00000165392/EFO_1001951

**Comment by DSuveges** [comment]
Based on communication with Stuart: 

> the CRIS types have been removed from the hypothesis files (Validation_Hypothesis_COlines_Expected_OTVL_CTG-CO_May2022.txt & Validation_Hypothesis_COlines_Observed_OTVL_CTG-CO_May2022.txt) which is what I thought was driving the population of all of the chips.
CRIS is still in the CO_Biomarkers.txt file because I still use that (for CRIS status) but Pan-Co status isn't and while that's in the top-line set of facets ("OTVL biomarker assessment for X") along with CRIS, it's not being displayed for individual cell-lines, e.g. for the gene CHD4 which is a Pan-Co hit & does get the green chip at the top.
>
>I think, for me, this boils down to two questions:
>
>* How are the chips in the  "OTVL biomarker assessment for X" panel populated (or rather, which file(s) are they populated from)?
>* Is population of these independent of the population of the "Cell line biomarkers" column in the per-cell line table?
>
>I thought the answer to the second one was "no" (so only biomarkers detected in the hypothesis files would be extracted from CO_Biomarkers.txt) but it looks like the answer is really yes, which is actually cool because it allows us to not display Pan-Co in gene contexts where it could be confusing.
>
>So - if the answer to the second question is indeed "yes", and the answer to the first one is "CO_Biomarkers.txt" for the per-cell line table and both of the hypothesis files for the "OTVL biomarker assessment for X" section, with no cross-talk between the two, I can just remove CRIS from CO_Biomarkers.txt before passing it over in future and there's no need to change the ingest.
... so a long winded way of saying: "should I just delete the column from CO_Biomarkers.txt?"
```

**Comment by buniello** [comment]
It sounds like the right way to go for me! @DSuveges

**Comment by DSuveges** [comment]
After a discussion, I decided to add a condition to the validation lab parser to remove CRIS annotation from the biomarker list. [here](https://github.com/opentargets/evidence_datasource_parsers/pull/115/commits/33fd03735151adee0484fb5f6099147c27383e31). As the display of biomarkers depend on the provided data, there's no expected change on the front-end.
